<?php
include 'config/db.php';

if(!isset($_GET['id'])) exit("No ID");

$id = $_GET['id'];
$res = $conn->query("SELECT * FROM sent_itineraries WHERE id=$id");
$row = $res->fetch_assoc();

$filename = preg_replace('/[^A-Za-z0-9\-]/', '_', $row['custom_title']) . ".doc";

header("Content-Type: application/vnd.ms-word");
header("Expires: 0");
header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
header("content-disposition: attachment;filename=$filename");

echo "<html>";
echo "<head><meta http-equiv='Content-Type' content='text/html; charset=utf-8'></head>";
echo "<body>";
echo "<h1 style='color:blue;'>" . $row['custom_title'] . "</h1>";
echo "<p><strong>Price Quote: $" . $row['final_price'] . "</strong></p>";
echo "<hr>";
echo "<div>" . $row['custom_content'] . "</div>";
echo "<hr>";
echo "<p>Generated by Itinerary Data Bank System</p>";
echo "</body>";
echo "</html>";
?>